### ISSUE TITLE
Create a `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/runbook#1]
https://github.blog/2012-09-17-contributing-guidelines/

These files are prompted whenever opening a PR / issue automatically. It would be a useful medium of documenting how to contribute effectively and what the repo should / should not contain etc etc.

**Comment by trickeydan** [comment]
It would be good to use [CLA Assistant](https://cla-assistant.io/) as well to ensure that people agree.

**Comment by RealOrangeOne** [comment]
Quite possibly. I think that's something worth raising / considering as part of #3

**Comment by PeterJCLaw** [comment]
Not sure if this is quite the right place to put this, but worth recording and not sure it's worth a separate issue, would be that we should have a list of principles that we aspire to in these docs.

Here's the list I've been using (in my head), which I think mirrors the discussion we first had when we talked about setting up the docs platform:
- aim to record the reasons _why_ things happen, because:
  - this provides context for a task or behaviour, which generally leads to better understanding
  - so that it's easier to understand when a thing is outdated or no longer relevant
  - so we don't need to re-learn why a thing is important
- for any processes, try to ensure there are no dead ends. For example, if we need to contact someone about something, ensure the person being contacted will have the ability to resolve the situation rather than themselves needing to contact someone else. (Note that contact-by-proxy is ok, as long as the eventual recipient meets the preceding criteria)
- for any year-specific stuff, ensure that it's either clearly marked as such or consider whether somewhere else is a better place for it; having a separate file prefixed by e.g: `sr2019` is a good way to mark this sort of thing
- try not to duplicate existing documentation (e.g: of tooling)
  - if we feel it can be improved generally we should contribute upstream
  - however, a custom how-to guide _is_ ok
- having some docs outside the runbook is ok, as long as there's a reason for it and there's good signposting. Examples: https://github.com/srobo/kit-maintenance-docs (has Python scripts and is fairly standalone), https://github.com/srobo/kit-coordination-documents (has LaTeX source and needs a build system)

If I think of any others I'll add to that list.

**Comment by PeterJCLaw** [comment]
A little separately, it might also be worth having some template pages. For example on new roles that would include some of the common headings (Setup, Equipment list, etc.).

**Comment by PeterJCLaw** [comment]
We should also decide whether process docs are written _to_ a role ("You'll need to do ..") or _about_ a role ("The person in this role will need to do ..").
