### ISSUE TITLE
Merge in legacy kit-logistic docs

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/runbook#18]
https://srobo-legacy.gitbooks.io/student-robotics-kit-logistics/

@richardbarlow do you happen to know where the source code to that publication is? (Rather than us re-creating it from the published HTML)

**Comment by richardbarlow** [comment]
You can clone it from https://git.gitbook.com/srobo-legacy/student-robotics-kit-logistics.git

Note that it requests HTTP auth user/password, however entering any random text allows you to clone it. Also note that the 'legacy' in the org name is due to it still being on the 'legacy' GitBook platform. Unfortunately they had a complete re-write which I feel lost the biggest selling point for me - a fully hosted git-centric documentation platform. In the re-write they sort of forgot about the whole git-centric thing and it now feels more like an afterthought. The Trustee's ops-manual is under the 'srobo' GitBook org, which is on the new platform and I don't like it as much.
